version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"
    open-pull-requests-limit: 10
    groups:
      nats:
        patterns:
          - "@nats-io/*"
      cloudflare:
        patterns:
          - "@cloudflare/*"
      dev:
        dependency-type: "development"
        exclude-patterns:
          - "@cloudflare/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore(ci):"
